---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kubepi-deployment
  name: kubepi
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepi
  template:
    metadata:
      labels:
        app: kubepi
    spec:
      nodeName: fanym-master-1
      containers:
      - image: kubeoperator/kubepi-server:latest
        name: kubepi
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/kubepi"
          name: var-lib-kubepi
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      volumes:
      - name: var-lib-kubepi
        persistentVolumeClaim:
          claimName: kubepi-pvc
