kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubepi-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: master-nfs
